### ISSUE TITLE
ReactDOM is not defined

### ISSUE THREAD

**Issue by kolf** [danielronnkvist/react-hover-scrub#1]
react-hover-scrub.js?ba78:99Uncaught ReferenceError: ReactDOM is not defined

**Comment by danielronnkvist** [comment]
This package has _react_ and _react-dom_ as peer dependencies. Include them in your project to be able to use it.

The peer dependencies wasn't specified in the package.json, I will add them to the next release.

**Comment by kolf** [comment]
What should i do? Suppose I had to use it

**Comment by danielronnkvist** [comment]
Checkout the [getting started](https://facebook.github.io/react/docs/getting-started.html#starter-pack) section on react. Or take a look at the branch `gh-pages` of this repo. Especially the file [index.html](https://github.com/danielronnkvist/react-hover-scrub/blob/gh-pages/index.html), it includes the most basic usage.

**Comment by kolf** [comment]
https://github.com/kolf/damweb This is my project, I must use it.Please help me to look at

**Comment by danielronnkvist** [comment]
Sorry, please come back with more specific questions/issues regarding my project. Closing this issue now, feel free to reopen if you discover something. A new version is up on NPM with react and react-dom as peer dependencies.
